'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import type { components } from '../../../types/api';
import '../../campus.css';

type Course = components['schemas']['CourseDetail'];
type Lesson = components['schemas']['LessonContent'];
type Enrollment = components['schemas']['EnrollmentItem'];

export default function LearnPage() {
  const { slug } = useParams<{ slug: string }>(); const [course, setCourse] = useState<Course | null>(null); const [lesson, setLesson] = useState<Lesson | null>(null); const [enrollment, setEnrollment] = useState<Enrollment | null>(null); const [selected, setSelected] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function loadProgress(courseId: string) { const res = await fetch('/api/campus/enrollments/me', { cache: 'no-store' }); if (!res.ok) throw new Error('Connecte-toi pour accéder à ta formation.'); const body = await res.json() as components['schemas']['EnrollmentPage']; const found = body.items.find((entry) => entry.course_id === courseId); if (!found) throw new Error('Inscris-toi à la formation pour accéder aux leçons.'); setEnrollment(found); }
  async function openLesson(id: string) { setSelected(id); setLesson(null); setError(''); try { const res = await fetch(`/api/campus/lessons/${id}`, { cache: 'no-store' }); const body = await res.json(); if (!res.ok) throw new Error(body.detail ?? 'Impossible d’ouvrir cette leçon.'); setLesson(body as Lesson); } catch (e) { setError(e instanceof Error ? e.message : 'Impossible d’ouvrir cette leçon.'); } }
  useEffect(() => { let active = true; (async () => { try { const response = await fetch(`/api/campus/courses/${encodeURIComponent(slug)}`); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? 'Formation introuvable.'); const item = body as Course; if (!active) return; setCourse(item); await loadProgress(item.id); const first = item.modules[0]?.lessons[0]; if (first) await openLesson(first.id); } catch (e) { if (active) setError(e instanceof Error ? e.message : 'Impossible de charger la formation.'); } })(); return () => { active = false; }; }, [slug]);
  async function completeLesson() { if (!lesson) return; setBusy(true); setError(''); try { const response = await fetch('/api/campus/progress/complete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ lesson_id: lesson.id }) }); const result = await response.json(); if (!response.ok) throw new Error(result.detail ?? 'La progression ne peut pas être enregistrée.'); setLesson({ ...lesson, is_completed: true }); if (enrollment) setEnrollment({ ...enrollment, progress_percent: result.course_progress.progress_percent, completed_lessons: result.course_progress.completed_lessons, total_lessons: result.course_progress.total_lessons, status: result.course_progress.enrollment_status }); await loadProgress(course!.id); } catch (e) { setError(e instanceof Error ? e.message : 'La progression ne peut pas être enregistrée.'); } finally { setBusy(false); } }
  const lessons = course?.modules.flatMap((module) => module.lessons.map((item) => ({ ...item, moduleTitle: module.title }))) ?? [];
  return <main className="campus-shell learn-shell"><nav className="campus-nav"><Link href="/campus" className="campus-brand"><span className="campus-mark">✳</span> IVOIREX <span className="nav-divider">/</span> Campus</Link><Link href={`/campus/${slug}`}>Quitter le cours</Link></nav>{course && <><header className="learn-header"><div><div className="campus-kicker">TON PARCOURS</div><h1>{course.title}</h1></div><div className="learn-progress"><div><span>Progression sauvegardée</span><b>{enrollment?.progress_percent ?? 0}%</b></div><span className="progress-track"><i style={{ width: `${enrollment?.progress_percent ?? 0}%` }}/></span><small>{enrollment?.completed_lessons ?? 0} / {enrollment?.total_lessons ?? lessons.length} leçons terminées</small></div></header><div className="learn-layout"><aside className="lesson-sidebar"><div className="campus-kicker">CONTENU DU COURS</div>{course.modules.map((module, index) => <section className="learn-module" key={module.id}><h2><span>{String(index+1).padStart(2,'0')}</span>{module.title}</h2>{module.lessons.map((item) => { const done = item.id === selected ? lesson?.is_completed : false; return <button className={`lesson-link ${selected === item.id ? 'active' : ''}`} key={item.id} onClick={() => openLesson(item.id)}><span className="lesson-check">{done ? '✓' : '○'}</span><span>{item.title}<small>{item.duration_minutes} min</small></span></button>; })}</section>)}</aside><article className="lesson-content">{error && <p className="message error" role="alert">{error}</p>}{lesson ? <><div className="campus-kicker">{lesson.module_title} · {lesson.duration_minutes} MIN</div><h2>{lesson.title}</h2><div className="lesson-prose">{lesson.content.split('\n').map((line, i) => line.trim() ? <p key={i}>{line}</p> : null)}</div><div className="lesson-actions">{lesson.is_completed ? <span className="lesson-done">✓ Leçon terminée · progression enregistrée</span> : <button className="campus-cta" onClick={completeLesson} disabled={busy}>{busy ? 'Enregistrement…' : 'Marquer comme terminée'} <span>✓</span></button>}</div><div className="lesson-nav">{lessons.map((item, i) => item.id === selected && lessons[i + 1] ? <button key={item.id} onClick={() => openLesson(lessons[i+1].id)}>Leçon suivante <span>→</span></button> : null)}</div></> : !error && <p className="catalog-state">Chargement de la leçon…</p>}</article></div></>}</main>;
}
